USE DataWarehouseAnalytics;
GO

-- find total customers by country
SELECT country, COUNT(customer_key) AS TotalCustomers
FROM gold.dim_customers
GROUP BY country
ORDER BY TotalCustomers;

-- find total customers by gender
SELECT gender, COUNT(customer_key) AS TotalCustomers
FROM gold.dim_customers
GROUP BY gender

-- find total product by category
SELECT category,COUNT(product_key) AS TotalProducts
FROM gold.dim_products
GROUP BY category

-- what is the average cost of each category
SELECT category,AVG(cost) AS AverageCost
FROM gold.dim_products
GROUP BY category

-- what is the total revenue generated by each category
SELECT P.category,SUM(f.sales_amount) AS TotalRevenue
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P 
ON F.product_key = P.product_key
GROUP BY P.category


-- what is the total revenue generated by each customer
SELECT C.customer_key,C.first_name,C.last_name,SUM(F.sales_amount) AS TotalRevenue
FROM gold.dim_customers C
RIGHT JOIN gold.fact_sales F
ON C.customer_key = F.customer_key
GROUP BY C.customer_key,C.first_name,C.last_name
ORDER BY TotalRevenue DESC

-- what is the distribution of items sold across countries
SELECT C.country, COUNT(F.product_key) AS TotalItemsSold
FROM gold.dim_customers C
RIGHT JOIN gold.fact_sales F
ON C.customer_key = F.customer_key
GROUP BY C.country
ORDER BY TotalItemsSold DESC
